#!/usr/bin/env python3
"""
Test script for GmailWatcher.

This script tests the GmailWatcher functionality without requiring
actual Gmail API access (uses mocking).
"""

import sys
from pathlib import Path
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))


def test_gmail_watcher_structure():
    """Test that GmailWatcher class exists and has required methods."""
    print("\n" + "="*60)
    print("GmailWatcher Structure Test")
    print("="*60)
    
    try:
        from watchers import GmailWatcher
        print("✓ GmailWatcher imported successfully")
        
        # Check required methods
        required_methods = [
            '_load_credentials',
            'check_for_updates',
            'create_action_file',
            '_get_message',
            '_get_message_body',
            'mark_as_read',
            'run'
        ]
        
        for method in required_methods:
            if hasattr(GmailWatcher, method):
                print(f"  ✓ Method: {method}")
            else:
                print(f"  ✗ Method missing: {method}")
                return False
        
        print("\n✓ All required methods present")
        return True
        
    except ImportError as e:
        print(f"✗ Failed to import GmailWatcher: {e}")
        return False
    except Exception as e:
        print(f"✗ Error: {e}")
        return False


def test_credentials_structure():
    """Test that credentials directory structure is correct."""
    print("\n" + "="*60)
    print("Credentials Structure Test")
    print("="*60)
    
    credentials_dir = Path(__file__).parent / 'credentials'
    
    # Check directory exists
    if credentials_dir.exists():
        print(f"✓ Credentials directory exists: {credentials_dir}")
    else:
        print(f"✗ Credentials directory missing: {credentials_dir}")
        print("  Run: python scripts/gmail_auth.py")
        return False
    
    # Check files
    files_to_check = {
        'credentials.json': 'Download from Google Cloud Console',
        'token.json': 'Generated by gmail_auth.py script'
    }
    
    all_present = True
    for filename, description in files_to_check.items():
        filepath = credentials_dir / filename
        if filepath.exists():
            print(f"  ✓ {filename}")
        else:
            print(f"  ✗ {filename} - {description}")
            all_present = False
    
    if not all_present:
        print("\n  Note: Missing files are OK for testing structure")
        print("  Run setup-gmail to generate them")
    
    return True


def test_action_file_format():
    """Test that action files are created with correct format."""
    print("\n" + "="*60)
    print("Action File Format Test")
    print("="*60)
    
    vault_path = Path(__file__).parent / 'AI_Employee_Vault'
    needs_action = vault_path / 'Needs_Action'
    
    # Create a mock action file
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    test_file = needs_action / f'TEST_EMAIL_{timestamp}.md'
    
    test_content = f"""---
type: email
from: test@example.com
subject: Test Email
received: {datetime.now().isoformat()}
priority: high
status: pending
gmail_id: test_123
---

# Email: Test Email

**From:** test@example.com

**Received:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Priority:** HIGH

---

## Email Content

This is a test email body.

---

## Suggested Actions

- [ ] Read and understand the email
- [ ] Determine if reply is needed
- [ ] Move to /Done when complete
"""
    
    try:
        needs_action.mkdir(parents=True, exist_ok=True)
        test_file.write_text(test_content)
        print(f"✓ Created test action file: {test_file.name}")
        
        # Verify content
        content = test_file.read_text()
        if 'type: email' in content and '---' in content:
            print("✓ Action file format is correct")
            
            # Cleanup
            test_file.unlink()
            print("✓ Cleaned up test file")
            return True
        else:
            print("✗ Action file format incorrect")
            return False
            
    except Exception as e:
        print(f"✗ Error creating test file: {e}")
        return False


def test_env_configuration():
    """Test that .env.example exists with correct structure."""
    print("\n" + "="*60)
    print("Environment Configuration Test")
    print("="*60)
    
    env_example = Path(__file__).parent / '.env.example'
    
    if env_example.exists():
        print(f"✓ .env.example exists")
        
        content = env_example.read_text()
        required_vars = [
            'GMAIL_CLIENT_ID',
            'GMAIL_CLIENT_SECRET',
            'GMAIL_REDIRECT_URI',
            'GMAIL_SCOPES'
        ]
        
        for var in required_vars:
            if var in content:
                print(f"  ✓ {var}")
            else:
                print(f"  ✗ {var} missing")
                return False
        
        return True
    else:
        print("✗ .env.example not found")
        return False


def run_all_tests():
    """Run all GmailWatcher tests."""
    print("\n" + "="*70)
    print("GmailWatcher Test Suite")
    print("="*70)
    
    tests = [
        ("Structure Test", test_gmail_watcher_structure),
        ("Credentials Test", test_credentials_structure),
        ("Action File Format Test", test_action_file_format),
        ("Environment Config Test", test_env_configuration),
    ]
    
    results = []
    for name, test_func in tests:
        try:
            result = test_func()
            results.append((name, result))
        except Exception as e:
            print(f"\n✗ {name} failed with exception: {e}")
            results.append((name, False))
    
    # Summary
    print("\n" + "="*70)
    print("Test Summary")
    print("="*70)
    
    passed = sum(1 for _, result in results if result)
    total = len(results)
    
    for name, result in results:
        status = "✓ PASS" if result else "✗ FAIL"
        print(f"  {status}: {name}")
    
    print(f"\nTotal: {passed}/{total} tests passed")
    
    if passed == total:
        print("\n✓ All GmailWatcher tests passed!")
        return True
    else:
        print(f"\n⚠ {total - passed} test(s) failed")
        return False


if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)
